apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.name}}
  {%- if values.description %}
  description: ${{values.description}}
  {%- endif %}
  annotations:
    github.com/project-slug: ${{values.destination.owner + "/" + values.destination.repo}}
spec:
  type: service
  owner: user:TigreDoMexico
  lifecycle: project
  system: ${{values.system}}