apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: template-nodejs-ts
  title: Node.js Typescript Template
  description: Template for Node.js with Typescript project
spec:
  owner: user:TigreDoMexico
  type: service

  parameters:
    - title: Informações Básicas
      required:
        - name
        - system
      properties:
        name:
          title: Nome do Projeto
          type: string
          description: Nome do novo projeto
          ui:autofocus: true
          ui:options:
            rows: 5
        description:
          title: Descrição
          type: string
          description: Para que é esse projeto
        system:
          title: Sistema
          type: string
          description: Em qual sistema esse projeto se encaixa
          ui:field: EntityPicker
          ui:options:
            allowedKinds:
              - System
            defaultKind: System
    - title: Informações do Repositório
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Informações do Repositório
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com

  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./template
        values:
          name: ${{ parameters.name }}

    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: This is ${{ parameters.name }}
        repoUrl: ${{ parameters.repoUrl }}

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}
